// Fleet package entrypoint (#122): daemon lifecycle, state, and (from later
// tickets) the scheduler, worktree coordinator, workers and telemetry bus.

export {
  APPROVE_TICKET_TTL_MS,
  type ApproveTicket,
  ApproveTickets,
  CsrfTokens,
} from "./approve.ts"
export type { StartDecision } from "./bin.ts"
export {
  awaitStartGrant,
  readStatusToken,
  START_GRANT_TIMEOUT_MS,
  START_GRANT_TYPE,
  STARTED_TIMEOUT_MS,
  STARTED_TYPE,
  startDecision,
  VERSION,
} from "./bin.ts"
export {
  type ConfigDrift,
  type ConfigPlan,
  type ConfigPlanInput,
  type ConfigView,
  planConfigFile,
  readConfigView,
} from "./configview.ts"
export { type DaemonOptions, FleetDaemon, type TransitionEvent, type WorkerPort } from "./daemon.ts"
export {
  type EvidenceClaimDetail,
  type EvidenceClaimFilter,
  type EvidenceClaimSummary,
  type EvidenceQuote,
  type EvidenceSourceView,
  EXPORT_CAP,
  exportEvidence,
  MAX_CLAIMS,
  readEvidenceClaim,
  readEvidenceClaims,
  readEvidenceSource,
  type SealStatus,
  SOURCE_TEXT_CAP,
} from "./evidence.ts"
export {
  assertHumanStart,
  FleetError,
  type FleetHandle,
  type FleetStatus,
  fleetStatus,
  isPidAlive,
  type StartOptions,
  startFleet,
  stopFleet,
} from "./lifecycle.ts"
export { readTaskLiveness, type TaskLiveness } from "./liveness.ts"
export {
  applyDecision,
  type CancelEntry,
  type Capacity,
  type Decision,
  markGateFailed,
  reportTask,
  schedule,
  type TaskReport,
} from "./scheduler.ts"
export { acquireSocket, SocketBusyError, type SocketGuard } from "./socket-guard.ts"
export {
  FLEET_STATE_VERSION,
  type FleetPaths,
  type FleetState,
  FleetStateSchema,
  fleetDir,
  fleetPaths,
  persistFleetState,
  readFleetState,
  stoppedState,
  writeFleetState,
} from "./state.ts"
export {
  addTask,
  DAG_VERSION,
  type DagState,
  DagStateSchema,
  emptyDag,
  type FailurePolicy,
  FailurePolicySchema,
  loadDag,
  saveDag,
  type Task,
  type TaskInput,
  TaskInputSchema,
  type TaskResult,
  TaskResultSchema,
  TaskSchema,
  type TaskStatus,
  TaskStatusSchema,
  TERMINAL,
  type Trigger,
  TriggerSchema,
  validateDag,
} from "./tasks.ts"
export {
  type BusEvent,
  EventLog,
  ensureToken,
  type FleetSnapshot,
  field,
  parseHeaders,
  readTelemetryEndpoint,
  type SnapshotTask,
  scrubPayload,
  type TelemetryOptions,
  TelemetryServer,
} from "./telemetry.ts"
export { readFleetSnapshot, renderDashboard, type WatchOptions, watchFleet } from "./watch.ts"
export {
  contentTypeFor,
  loopbackOriginOk,
  mintWebTicket,
  parseSessionCookie,
  redeemWebTicket,
  resolveWebFile,
  sessionSetCookie,
  WEB_SECURITY_HEADERS,
  WEB_SESSION_COOKIE,
  WEB_SESSION_TTL_MS,
  WEB_TICKET_TTL_MS,
  type WebFile,
  WebSessions,
} from "./web.ts"
export {
  type BreakerOptions,
  buildWorkerArgv,
  CircuitBreaker,
  defaultGateCheck,
  emptyAcc,
  type FoldedEvent,
  foldWorkerEvent,
  loadWorkerPids,
  prepareTaskRun,
  type SpendAcc,
  saveWorkerPids,
  Worker,
  type WorkerEnvelope,
  WorkerError,
  type WorkerOptions,
  type WorkerOutcome,
  type WorkerSpec,
  WorkerSupervisor,
} from "./worker.ts"
export {
  ALLOCATING_STALE_MS,
  type AllocateOptions,
  allocateWorktree,
  emptyRegistry,
  fleetBranch,
  fleetWorktreeDir,
  type GateCheck,
  type GcReport,
  gcWorktrees,
  integrationBranch,
  type LandResult,
  landTask,
  loadRegistry,
  mirrorDir,
  type ReleaseKind,
  rebaseSymlinks,
  releaseWorktree,
  salvageBranch,
  type WorktreeRecord,
  WorktreeRecordSchema,
  type WorktreeRegistry,
  WorktreeRegistrySchema,
  type WorktreeStatus,
  WorktreeStatusSchema,
  withRepoLock,
} from "./worktree.ts"
