// Fleet package entrypoint (#122): daemon lifecycle, state, and (from later
// tickets) the scheduler, worktree coordinator, workers and telemetry bus.
export { VERSION } from "./bin.ts"
export {
  assertHumanStart,
  FleetError,
  type FleetHandle,
  type FleetStatus,
  fleetStatus,
  isPidAlive,
  type StartOptions,
  startFleet,
  stopFleet,
} from "./lifecycle.ts"
export {
  applyDecision,
  type CancelEntry,
  type Capacity,
  type Decision,
  reportTask,
  schedule,
  type TaskReport,
} from "./scheduler.ts"
export { acquireSocket, SocketBusyError, type SocketGuard } from "./socket-guard.ts"
export {
  FLEET_STATE_VERSION,
  type FleetPaths,
  type FleetState,
  FleetStateSchema,
  fleetDir,
  fleetPaths,
  persistFleetState,
  readFleetState,
  stoppedState,
  writeFleetState,
} from "./state.ts"
export {
  addTask,
  DAG_VERSION,
  type DagState,
  DagStateSchema,
  emptyDag,
  type FailurePolicy,
  FailurePolicySchema,
  loadDag,
  saveDag,
  type Task,
  type TaskInput,
  TaskInputSchema,
  type TaskResult,
  TaskResultSchema,
  TaskSchema,
  type TaskStatus,
  TaskStatusSchema,
  TERMINAL,
  type Trigger,
  TriggerSchema,
  validateDag,
} from "./tasks.ts"
export {
  type AllocateOptions,
  allocateWorktree,
  emptyRegistry,
  fleetBranch,
  fleetWorktreeDir,
  type GateCheck,
  type GcReport,
  gcWorktrees,
  integrationBranch,
  type LandResult,
  landTask,
  loadRegistry,
  mirrorDir,
  type ReleaseKind,
  rebaseSymlinks,
  releaseWorktree,
  salvageBranch,
  type WorktreeRecord,
  WorktreeRecordSchema,
  type WorktreeRegistry,
  WorktreeRegistrySchema,
  type WorktreeStatus,
  WorktreeStatusSchema,
  withRepoLock,
} from "./worktree.ts"
export {
  CircuitBreaker,
  buildWorkerArgv,
  defaultGateCheck,
  emptyAcc,
  foldWorkerEvent,
  loadWorkerPids,
  prepareTaskRun,
  saveWorkerPids,
  Worker,
  WorkerError,
  WorkerSupervisor,
  type BreakerOptions,
  type FoldedEvent,
  type SpendAcc,
  type WorkerEnvelope,
  type WorkerOptions,
  type WorkerOutcome,
  type WorkerSpec,
} from "./worker.ts"
export { FleetDaemon, type DaemonOptions, type TransitionEvent, type WorkerPort } from "./daemon.ts"
